package com.spring.sxf.study.springtradedao.entry;

import java.util.Date;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.id
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.name
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.context
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.createDateTime
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    private Date createDateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.id
     *
     * @return the value of t_blog.id
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.id
     *
     * @param id the value for t_blog.id
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.name
     *
     * @return the value of t_blog.name
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.name
     *
     * @param name the value for t_blog.name
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.context
     *
     * @return the value of t_blog.context
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.context
     *
     * @param context the value for t_blog.context
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.createDateTime
     *
     * @return the value of t_blog.createDateTime
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    public Date getCreateDateTime() {
        return createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.createDateTime
     *
     * @param createDateTime the value for t_blog.createDateTime
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Thu Sep 26 17:15:45 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", context=").append(context);
        sb.append(", createDateTime=").append(createDateTime);
        sb.append("]");
        return sb.toString();
    }
}